### PR TITLE
Added ProblemDetailsException constructors

### PR DESCRIPTION
**Pull request by JonasSamuelsson**
this set of constructors makes to code for throwing exceptions that translates into a status code response a little more terse and easier to read/write

for example:
``` csharp
throw new ProblemDetailsException(HttpStatusCode.BadRequest, "Invalid data");
```
vs
``` csharp
throw new ProblemDetailsException(new StatusCodeProblemDetails(HttpStatusCode.BadRequest) { Title = "Invalid data" });
```
would you be willing to accept this?

### CODE REVIEW

**Comment by khellang** [comment]
Sure, but I'm not sure the `System.Net.HttpStatusCode` enum is necessary. Using `Microsoft.AspNetCore.Http.StatusCodes` should be enough.

**Comment by JonasSamuelsson** [comment]
I think that from a usability perspective the enum version really helps, just type `new pde`, `Enter`, `ctrl+space` and intellisense kicks in with a list of valid values. `Microsoft.AspNetCore.Http.StatusCodes` isn't all that discoverable.

Willing to reconsider? otherwise I'll go ahead and update the pr

**Comment by khellang** [comment]
I'd like to keep the code based aligned with what ASP.NET Core is doing, and they're using `int`. Fundamentally, HTTP status codes isn't a closed set, so using enums is kinda problematic. I've pushed for using alternatives many many times, starting around 4-5 years ago (see https://github.com/aspnet/HttpAbstractions/pull/345), but I'm afraid that ship has sailed.

**Comment by JonasSamuelsson** [comment]
I agree with you that an enum might be problematic, that's why I also added overloads taking an int.
But I'll go ahead and remove the enum contructors if that is how you want it.

**Comment by JonasSamuelsson** [comment]
Are you expecting anything else from me on this one?

**Comment by khellang** [comment]
> Are you expecting anything else from me on this one?

Nope. Thanks for the contribution! ❤️

**Pull request merged**
