### PR TITLE
update readme for sample app

### PR DESCRIPTION
**Pull request by christianacca**
Updated sample app to 3.1; readme for the library needs updating to reflect that

BTW, also made a couple changes to the the sample app:
* use the latest version of Hellang.Middleware.ProblemDetails package
* tweaking some existing code to make it use the newer features of the package
* added comments explaining the conventions setup in the sample app and contrasting them to conventions set by `AddProblemDetailsConventions`

### CODE REVIEW

**Comment by khellang** [comment]
Hah, nice one @christianacca! You're awesome. Thanks! 😎🙏

**Comment by khellang** [comment]
Hmm... This one should definitely be fixed 🤔

> * AddProblemDetailsConventions: BadRequest(ModelState) does NOT produce a problem detail response

**Comment by khellang** [comment]
I'd also like to start adding some knobs to the MVC part of the library, like the default status code for validation problems 😊

**Comment by christianacca** [comment]
That would be perfect :-)

**Pull request merged**
